version: '2'
services:
  susalud_back-app:
    image: susalud_back
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://susalud_back-mssql:1433;database=suSalud
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8090:8090
  susalud_back-mssql:
    extends:
      file: mssql.yml
      service: susalud_back-mssql
